#!/usr/bin/env python3

from . import db

TRAP_HTTP_EXCEPTIONS = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_POOL_TIMEOUT = 600
SQLALCHEMY_MAX_OVERFLOW = 100
SESSION_TYPE = 'sqlalchemy'
SESSION_SQLALCHEMY = db
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
