#!/usr/bin/env python3

from . import db

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 100
SQLALCHEMY_POOL_TIMEOUT = 600
SQLALCHEMY_MAX_OVERFLOW = 100
SESSION_TYPE = 'sqlalchemy'
SESSION_SQLALCHEMY = db
SECURITY_POST_RESET_VIEW = '/'
SECURITY_POST_CHANGE_VIEW = 'Home.profile'
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
