#!/usr/bin/env python3

from . import db

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 1000
SQLALCHEMY_POOL_TIMEOUT = 600
SQLALCHEMY_MAX_OVERFLOW = 1000
SESSION_TYPE = 'sqlalchemy'
SESSION_SQLALCHEMY = db
