from . import redisInstance

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 1000
SQLALCHEMY_POOL_TIMEOUT = 120
SQLALCHEMY_POOL_RECYCLE = 115
SQLALCHEMY_MAX_OVERFLOW = 1000
SQLALCHEMY_ECHO = False
SESSION_TYPE = 'redis'
SESSION_REDIS = redisInstance
SECURITY_POST_CHANGE_VIEW = 'Home.profile_home'
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
UPLOADS_DEFAULT_DEST = '/var/uploads'
WTF_CSRF_TIME_LIMIT = None
